// <auto-generated />
namespace SalesManagementSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class last24 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(last24));
        
        string IMigrationMetadata.Id
        {
            get { return "202401211931581_last24"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
